;----------------------- Arquivos Atuais ----------------------------
;Se houver a versão do arquivo o mesma sera utiliza para comparação
;caso contrário o arquivo será copiado do servidor para a estação 
;sem comparação de versão, as chaves que forem adicioandos no arquivo 
;do servirdor serão criadas no arquivo da estação
[Arquivos]
Copia=crpe32.dll,9.2.3.7001;crue32.dll,9.2.3.2000;extens32.dll;biblioteca.exe;
