object frmRepContrato: TfrmRepContrato
  Left = 175
  Top = 147
  Width = 190
  Height = 93
  Caption = 'frmRepContrato'
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object Report: TppReport
    DataPipeline = ppContrato
    PrinterSetup.BinName = 'Default'
    PrinterSetup.Copies = 2
    PrinterSetup.DocumentName = 'Contrato...'
    PrinterSetup.PaperName = 'A4 (210 x 297 mm)'
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.mmMarginBottom = 2000
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 2000
    PrinterSetup.mmPaperHeight = 297000
    PrinterSetup.mmPaperWidth = 210000
    Template.FileName = 'C:\Desenv\Universitario\repContrato.RTM'
    Units = utMillimeters
    Device = dvPrinter
    Language = lgPortugueseBrazil
    ShowPrintDialog = False
    Left = 120
    Top = 16
    Version = '3.52'
    mmColumnWidth = 0
    object ppReport1HeaderBand1: TppHeaderBand
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
    object ppReport1DetailBand1: TppDetailBand
      mmBottomOffset = 0
      mmHeight = 287867
      mmPrintPosition = 0
      object ppReport1RichText1: TppRichText
        Caption = 'ppReport1RichText1'
        RichText = 
          '{\rtf1\ansi\deff0\deftab720{\fonttbl{\f0\fswiss MS Sans Serif;}{' +
          '\f1\froman\fcharset2 Symbol;}{\f2\fswiss\fcharset1 MS Sans Serif' +
          ';}{\f3\froman\fprq2 Times New Roman;}}'#13#10'{\colortbl\red0\green0\b' +
          'lue0;}'#13#10'\deflang1046\pard\qc\plain\f3\fs18\b\ul CONTRATO DE PRES' +
          'TA\'#39'c7\'#39'c3O DE SERVI\'#39'c7OS EDUCACIONAIS'#13#10'\par '#13#10'\par '#13#10'\par \par' +
          'd\plain\f3\fs18\b '#13#10'\par '#13#10'\par '#13#10'\par '#13#10'\par '#13#10'\par '#13#10'\par \pla' +
          'in\f3\fs18 '#13#10'\par '#13#10'\par '#13#10'\par '#13#10'\par Cl\'#39'e1usula 2\'#39'aa)\plain\' +
          'f3\fs18\b  \plain\f3\fs18  As aulas ser\'#39'e3o ministradas em loca' +
          'is pr\'#39'f3prios para tal, indicados pela ESCOLA e de acordo com a' +
          ' natureza dos conte\'#39'fados e das t\'#39'e9cnicas pedag\'#39'f3gicas que ' +
          'se fizerem necess\'#39'e1rias.'#13#10'\par Cl\'#39'e1usula 3\'#39'aa)\plain\f3\fs1' +
          '8\b  \plain\f3\fs18 A formaliza\'#39'e7\'#39'e3o do ato de matr\'#39'edcula ' +
          'se procede pelo preenchimento e assinatura do formul\'#39'e1rio forn' +
          'ecido pela ESCOLA, denominado REQUERIMENTO DE MATR\'#39'cdCULA, o qu' +
          'al \'#39'e9 parte integrante deste contrato.'#13#10'\par Par\'#39'e1grafo 1\'#39'b' +
          'a:  O requerimento de matr\'#39'edcula somente ser\'#39'e1 encaminhado p' +
          'ara exame e deferimento pelo Diretor ap\'#39'f3s certifica\'#39'e7\'#39'e3o ' +
          'pela Tesouraria de que o CONTRATANTE quitou todas as obriga\'#39'e7\' +
          #39'f5es financeiras decorrentes de presta\'#39'e7\'#39'f5es anteriores e p' +
          'revistas para o ato de matr\'#39'edcula.'#13#10'\par Cl\'#39'e1usula 4\'#39'aa) Ao' +
          '  firmar o presente contrato, o CONTRATANTE e o aluno submetem-s' +
          'e ao Regimento Escolar da ESCOLA e demais disposi\'#39'e7\'#39'f5es da L' +
          'egisla\'#39'e7\'#39'e3o Escolar vigente.'#13#10'\par  '#13#10'\par '#13#10'\par Par\'#39'e1gra' +
          'fo 1\'#39'ba:  Os pre\'#39'e7os estipulados para cada um dos Cursos resu' +
          'ltam de or\'#39'e7amento de custos e receitas elaborado no m\'#39'eas de' +
          ' junho de 1999.'#13#10'\par Par\'#39'e1grafo 2\'#39'ba:  O pre\'#39'e7o aven\'#39'e7ad' +
          'o no caput poder\'#39'e1 ser alterado por for\'#39'e7a de Lei, Medida Pr' +
          'ovis\'#39'f3ria, decis\'#39'e3o judicial ou senten\'#39'e7a normativa de tra' +
          'balho que implique comprovada altera\'#39'e7\'#39'e3o nos custos ou rece' +
          'itas previstos no or\'#39'e7amento mencionado no par\'#39'e1grafo 1\'#39'ba ' +
          'desta cl\'#39'e1usula, de modo a manter o equil\'#39'edbrio na equa\'#39'e7\' +
          #39'e3o econ\'#39'f4mico-financeira resultante do presente contrato.'#13#10'\' +
          'par '#13#10'\par Cl\'#39'e1usula 6\'#39'aa:  O pagamento das parcelas dever\'#39'e' +
          '1 ser feito em Banco autorizado para tal, ou, a crit\'#39'e9rio da E' +
          'SCOLA, na Tesouraria.'#13#10'\par Par\'#39'e1grafo 1\'#39'ba:  As parcelas ven' +
          'cer\'#39'e3o no dia 1\'#39'ba de cada m\'#39'eas, podendo ser pagas sem qual' +
          'quer acr\'#39'e9scimo at\'#39'e9 o 5\'#39'ba dia \'#39'fatil.'#13#10'\par Par\'#39'e1grafo' +
          ' 2\'#39'ba: O n\'#39'e3o pagamento das parcelas na data aven\'#39'e7ada impl' +
          'icar\'#39'e1 na perda de eventuais bonifica\'#39'e7\'#39'f5es, al\'#39'e9m da in' +
          'cid\'#39'eancia de multa de 2% e corre\'#39'e7\'#39'e3o monet\'#39'e1ria pelos \' +
          #39'edndices da caderneta de poupan\'#39'e7a, m\'#39'eas a m\'#39'eas, a partir' +
          ' da data do vencimento da parcela e at\'#39'e9 seu efetivo pagamento' +
          ', bem como despesas extrajudiciais, judiciais e honor\'#39'e1rios ad' +
          'vocat\'#39'edcios decorrentes da cobran\'#39'e7a. '#13#10'\par Par\'#39'e1grafo 3\' +
          #39'ba:  Quanto aos d\'#39'e9bitos vencidos e n\'#39'e3o pagos no prazo est' +
          'ipulado, a ESCOLA fica desde j\'#39'e1 autorizada a emitir t\'#39'edtulo' +
          ' de cr\'#39'e9dito contra o devedor no valor da(s) parcela(s) vencid' +
          'a(s), acrescida(s) de todas as comina\'#39'e7\'#39'f5es e acr\'#39'e9scimos ' +
          'previstos no par\'#39'e1grafo 2\'#39'ba desta cl\'#39'e1usula.'#13#10'\par Par\'#39'e1' +
          'grafo 4\'#39'ba: Em caso de inadimpl\'#39'eancia ou atraso de qualquer d' +
          'as parcelas ajustadas na cl\'#39'e1usula 5\'#39'aa e seus par\'#39'e1grafos ' +
          'ou de qualquer outro pagamento decorrente do presente contrato, ' +
          'por 30 (trinta) dias ou mais, fica ciente o contratante que o fa' +
          'to ser\'#39'e1 comunicado ao cadastro de devedores legalmente existe' +
          'nte para registro (SPC), nos termos do art. 43, par\'#39'e1grafo 2\'#39 +
          'ba da lei 8078/90 (C\'#39'f3digo de Defesa do Consumidor).'#13#10'\par Par' +
          '\'#39'e1grafo 5\'#39'ba: Em caso de inadimpl\'#39'eancia, o CONTRATANTE, a c' +
          'rit\'#39'e9rio da ESCOLA, perder\'#39'e1 o direito \'#39'e0 vaga e rematr\'#39'e' +
          'dcula do aluno para o ano letivo subseq\'#39'fcente, caso n\'#39'e3o sej' +
          'a saldado o d\'#39'e9bito at\'#39'e9 a data da matr\'#39'edcula, sem preju\'#39 +
          'edzo da cobran\'#39'e7a extrajudicial e judicial dos encargos educac' +
          'ionais devidos com os acr\'#39'e9scimos e comina\'#39'e7\'#39'f5es legais pr' +
          'evistas no par\'#39'e1grafo 2\'#39'ba desta cl\'#39'e1usula.'#13#10'\par Cl\'#39'e1usu' +
          'la 7\'#39'aa) Os valores ajustados na cl\'#39'e1usula 5\'#39'aa referem-se e' +
          'xclusivamente \'#39'e0 presta\'#39'e7\'#39'e3o de servi\'#39'e7os decorrentes da' +
          ' carga hor\'#39'e1ria constante no Plano Escolar.'#13#10'\par Par\'#39'e1grafo' +
          ' 1\'#39'ba:  Os valores da contrapresta\'#39'e7\'#39'e3o das demais atividad' +
          'es, inclusive as extracurriculares, ser\'#39'e3o fixados a cada serv' +
          'i\'#39'e7o pela ESCOLA, e n\'#39'e3o ter\'#39'e3o car\'#39'e1ger obrigat\'#39'f3rio.' +
          #13#10'\par Par\'#39'e1grafo 2\'#39'ba:  N\'#39'e3o est\'#39'e3o inclu\'#39'eddos neste c' +
          'ontrato os servi\'#39'e7os especiais de recupera\'#39'e7\'#39'e3o, refor\'#39'e7' +
          'o, depend\'#39'eancia, transporte escolar, os opcionais e uso facult' +
          'ativo para o aluno, as segundas chamadas de provas ou exames, as' +
          ' segundas vias de documentos, o uniforme e a alimenta\'#39'e7\'#39'e3o.'#13 +
          #10'\par '#13#10'\par Cl\'#39'e1usula 8\'#39'aa)\plain\f3\fs18\b  \plain\f3\fs18 ' +
          'Em caso de inadimpl\'#39'eancia, a crit\'#39'e9rio da ESCOLA, poder\'#39'e3o' +
          ' ser aplicadas as san\'#39'e7\'#39'f5es legalmente previstas, sem preju\' +
          #39'edzo daquelas acordadas no presente contrato.'#13#10'\par Cl\'#39'e1usula' +
          ' 9\'#39'aa) O presente contrato poder\'#39'e1 ser rescindido nos seguint' +
          'es casos: I - Pelo CONTRATANTE:  a) por desist\'#39'eancia do(a) alu' +
          'no, atrav\'#39'e9s de aviso escrito e protocolado na Secretaria/Teso' +
          'uraria da ESCOLA; b) por transfer\'#39'eancia de cidade, com pedido ' +
          'escrito e protocolado na Secretaria/Tesouraria da ESCOLA; II - P' +
          'ela ESCOLA: a) por desligamento nos termos do Regimento Escolar;' +
          ' b) por inadimpl\'#39'eancia.'#13#10'\par Par\'#39'e1grafo 1\'#39'ba:  Em todos os' +
          ' casos de rescis\'#39'e3o fica o CONTRATANTE obrigado a pagar o valo' +
          'r da parcela do m\'#39'eas em que ocorrer o evento, al\'#39'e9m de outro' +
          's d\'#39'e9bitos eventualmente existentes, com os acr\'#39'e9scimos e co' +
          'mina\'#39'e7\'#39'f5es previstos no par\'#39'e1grafo 2\'#39'ba da cl\'#39'e1usla 6\'#39 +
          'aa.'#13#10'\par Par\'#39'e1grafo 2\'#39'ba: Enquanto n\'#39'e3o for solicitado o c' +
          'ancelamento da matr\'#39'edcula pelo CONTRATANTE as parcelas do pre\' +
          #39'e7o aven\'#39'e7ado na cl\'#39'e1usula 5\'#39'aa continuar\'#39'e3o vencendo e ' +
          'ter\'#39'e3o que ser pagas mesmo que o(a) aluno(a) n\'#39'e3o assista \'#39 +
          'e0s aulas.'#13#10'\par Par\'#39'e1grafo 3\'#39'ba:  Em hip\'#39'f3tese alguma o CO' +
          'NTRATANTE ter\'#39'e1 direito ao reembolso de valores pagos \'#39'e0 CON' +
          'TRATADA, mesmo que o(a) aluno(a) n\'#39'e3o venha a freq\'#39'fcentar as' +
          ' aulas por qualquer motivo.'#13#10'\par Par\'#39'e1grafo 4\'#39'ba:  A desist\' +
          #39'eancia de que trata o item I, al\'#39'ednea "a" desta Cl\'#39'e1usula s' +
          'omente ser\'#39'e1 aceita se formalizada at\'#39'e9 60 dias antes do ter' +
          'mo final do contrato previsto na cl\'#39'e1usula 1\'#39'aa.  '#13#10'\par Par\' +
          #39'e1grafo 5\'#39'ba: O CONTRATANTE, a partir da assinatura do present' +
          'e instrumento, assume a responsabilidade pela veracidade da sua ' +
          'condi\'#39'e7\'#39'e3o de habilitado a frequentar o curso indicado na cl' +
          '\'#39'e1usula 1\'#39'aa, bem como da entrega dos documentos exig\'#39'edveis' +
          ' para o ato de matr\'#39'edcula.  Caso o CONTRATANTE venha a dar cau' +
          'sa, pela falta de qualquer requisito de matr\'#39'edcula v\'#39'e1lida, ' +
          'a circunst\'#39'e2ncia que n\'#39'e3o o habilite a freq\'#39'fcentar o curso' +
          ' de forma a surtir os efeitos legais de aquisi\'#39'e7\'#39'e3o de habil' +
          'ita\'#39'e7\'#39'f5es e, em raz\'#39'e3o disto, deixar de freq\'#39'fcentar o cu' +
          'rso, n\'#39'e3o ter\'#39'e1 direito ao reembolso dos valores j\'#39'e1 pagos' +
          ', tendo em vista que configuram pagamento a servi\'#39'e7os j\'#39'e1 pr' +
          'estados pela ESCOLA.'#13#10'\par Cl\'#39'e1usula 10\'#39'aa) As partes atribue' +
          'm ao presente contrato plena efic\'#39'e1cia executiva.'#13#10'\par Cl\'#39'e1' +
          'usula 11\'#39'aa) Fica eleito o foro da Comarca de Blumenau para dir' +
          'imir as quest\'#39'f5es oriundas do presente contrato.'#13#10'\par E por e' +
          'starem justos e contratados, assinam o presente instrumento em 2' +
          ' (duas)  vias de igual teor e forma na presen\'#39'e7a das testemunh' +
          'as abaixo, para que produza todos os seus jur\'#39'eddicos e legais ' +
          'efeitos.'#13#10'\par '#13#10'\par '#13#10'\par '#13#10'\par ____________________________' +
          '__                     _______________________________'#13#10'\par    ' +
          '    CONTRATANTE                                                 ' +
          '                 ESCOLA'#13#10'\par '#13#10'\par TESTEMUNHAS: ______________' +
          '____________              _________________________'#13#10'\par \plain' +
          '\f3\fs18\ul '#13#10'\par }'#13#10
        mmHeight = 282840
        mmLeft = 2117
        mmTop = 4498
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
      end
      object Memo: TppMemo
        Caption = 'Memo'
        CharWrap = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        mmHeight = 27252
        mmLeft = 2117
        mmTop = 11642
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmLeading = 0
      end
      object Memo2: TppMemo
        Caption = 'Memo'
        CharWrap = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        mmHeight = 11113
        mmLeft = 2117
        mmTop = 38629
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmLeading = 0
      end
      object Memo4: TppMemo
        Caption = 'Memo4'
        CharWrap = False
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        mmHeight = 5821
        mmLeft = 2117
        mmTop = 259557
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmLeading = 0
      end
      object Memo5: TppMemo
        Caption = 'Memo'
        CharWrap = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        mmHeight = 4498
        mmLeft = 2117
        mmTop = 175155
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmLeading = 0
      end
      object Memo6: TppMemo
        Caption = 'Memo'
        CharWrap = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        mmHeight = 4763
        mmLeft = 2117
        mmTop = 102129
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmLeading = 0
      end
      object Memo3: TppMemo
        Caption = 'Memo'
        CharWrap = True
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 9
        Font.Style = []
        Transparent = True
        mmHeight = 8996
        mmLeft = 2117
        mmTop = 80433
        mmWidth = 189971
        BandType = 4
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmLeading = 0
      end
      object ReportImage1: TppImage
        MaintainAspectRatio = False
        Stretch = True
        Transparent = True
        Picture.Data = {
          07544269746D6170BE610000424DBE610000000000003E00000028000000F602
          000004010000010001000000000080610000C40E0000C40E0000020000000000
          000000000000FFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFE7FFFFFFFFFFFFC1FFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF9FFFFFFFFFFFF9E7FFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFCFFFFFFFFFFFF9F8FFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFF7FFFFFFFFFFFDFF1FFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFF9FFFFFFFFFFFDFFE7FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFEFFFFFFFFFFFEFFF9FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFF3FFFFFFFFFFF7FFE7FFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFF9FFFFFFFFFFF7FFF9FFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFEFFFFFFFFFFFBFFFE7FFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFF3FFFFFFFFFFDFFFF9FFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFDFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFF7FFFFFFFFFF7FFFF9FFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFBFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFDFFFFFFFFFFBFFFFF3FFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFF7FFFFFFFFFDFFFFFE7FFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFBFFFFFFFFFEFFFFFF3FFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFCFFFFFFFFFF7FFFFFCFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF3FFFFFFFFFBFFFFFF3FFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFDFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFE7FFFFFFFFEFFFFFFF3FFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFF9FFFFFFFFF7FFFFFFCFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF3FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFF7FFFFFFFFDFFFFFFF9FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFE7FFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFBFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFF3FFFFFFFFBFFFFFFFCFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFCFFFFFFFFEFFFFFFFF3FFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFE7FFFFFFFF7FFFFFFFCFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFF3FFFFFFFFBFFFFFFFE7FFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFCFFFFFFFFDFFFFFFFF9FFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFF3FFFFFFFEFFFFFFFFE7FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFF9FFFFFFFF7FFFFFFFF3FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFCFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF07FFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFBFFFFFFFDFFFFFFFFF3FFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0FFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFDFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE07FFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFF3FFFFFFFBFFFFFFFFE7FFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF81FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFF9FFFFFFFDFFFFFFFFF9FFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFE7FFFFFFEFFFFFFFFFEFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFF8007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF1FFFFFFF7FFFFFFFFF3FFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFF0003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFDFFFFFFFDFFFFFFFFF9FFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFC003FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFE7FFFFFFEFFFFFFFFFE7FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFC0007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFF9FFFFFFF7FFFFFFFFF9FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFC0001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFEFFFFFFF9FFFFFFFFFE7FFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFF80001FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFF3FFFFFFDFFFFFFFFFF3FFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFCFFFFFFF7FFFFFFFFFCFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0
          00000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFBFFFFFFFFFE3FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8000003F
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFBFFFFFFDFFFFFFFFFF9FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF4000000000FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFE7FFFFFFFFFC3F
          FFFFE7FFFFFFFFFFFFFFFFFFFFFFFFF100000000000001BFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFF3FFF00000000007FFF3F
          FFFFFFFFEF79D2040820000000305FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFC0000FFFFDFFFFFFFFFFCF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFF807FFE7FFFFFEFFFFFFFFFFF7
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFF03FFFFFF9FFFFFF7FFFFFFFFFF9
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFC1FFFFFFFFFC7FFFFFFFFFFFFFFFFE
          7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFC3FFFFFFFFFFF7FFFFFCFFFFFFFFFFF
          3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF87FFFFFFFFFFFF9FFFFFEFFFFFFFFFFF
          CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFF3FFFFFFFFFFFFFFE7FFFFF3FFFFFFFFFF
          F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFF8FFFFFFFFFFFFFFFF3FFFFF9FFFFFFFFFF
          F9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFC7FFFFFFFFFFFFFFFFCFFFFFEFFFFFFFFFF
          FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFE7FFFFFFFFFFFFFFFFFF3FFFFF7FFFFFFFFF
          FF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFF9FFFFFFFFFFFFFFFFFFF9FFFFF9FFFFFFFFF
          FFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFF7FFFFFFFFFFFFFFFFFFFE7FFFFCFFFFFFFFF
          FFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFF9FFFFFFFFFFFFFFFFFFFFF9FFFFF7FFFFFFFF
          FFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFF7FFFFFFFFFFFFFFFFFFFFFCFFFFFBFFFFFFFF
          FFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFE7FFFFFFFFFFFFFFFFFFFFFE3FFFFDFFFFFFFF
          FFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFDFFFFFFFFFFFFFFFFFFFFFFFCFFFFE7FFFFFFF
          FFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF9FFFFFFFFFFFFFFFFFFFFFFFE3FFFFBFFFFFFF
          FFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFBFFFFDFFFFFFF
          FFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFEFFFFE7FFFFFF
          FFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFF3FFFF3FFFFFF
          FFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFCFFFF9FF01FF
          FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFE7FFFEFC7E07
          FFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFF9FFFF31FFF8
          3FFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFCFFFF93FFFF
          C3FFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFC3FFFF
          FC3FFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFF1FFFF
          FFC3FFFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFF9FFFF
          FFFE3FFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFCFFFF
          FFFFE3FFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFE7FFF
          FFFFFE7FFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF83FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFF
          FFFFFFC7FF3FFFFFFFFFFFFFF80FFFFFFFFFFFFFFFFFFFFFFFFFFF98FFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFF
          FFFFFFFE7F9FFFFE7FFFFFFFE0C0FFFFFFF03FFFFFFFFFFFF0FFFFCC7FFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFF
          FFFFFFFFE3EFFFFC1FFC3FFFCFFE3FFFFFC38FFFFFFFFFBFE03F9FE73FFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFF
          FFFFFFFFFFF00FFC47FC8FE38FFF87FFFFC9E3FFFC1FFE07E31E03E79FFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7FFFFF
          FFFFFFFFFFF8C3FE23FC67C00FFFF1FFFFE4F8FFF987FE63E3CE78E7CFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFF
          FFFFFFFFFFFE78FF38FE39C70FFFFC7FFFF27E7FF9F3FE3CF3E03E73E3FFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFF
          FFFFFFFFFFFF9F1F9E3F3C47C7FFFF1FFFF93F9FFC7CFF3E39F83F19F1FFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFF
          FFFFFFFFFFFFCFC38F8F9F07F0FFFFC7FFF88FE7FE7E3F9F98FE1FD8FCFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFF
          FFFFFFFFFFFFF3F84FF1CFC3F87FFFF1FFFE63F9FF3F9FCFECFF0FE4FEFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7FFF
          FFFFFFFFFFFFF9FF07FC0FF1FE1FFFFC7FFF39FE7F9FE3C7F27FC7FA7F3FFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFF
          FFFFFFFFFFFFFE7FFFFFFFFFFF07FFFF1FFF9FFF8FCFF8E3FC3FE3FC7FBFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FF
          FFFFFFFFFFFFFF1FFFFFFFFFFF93FFFFCFFFCFFFE3E7FE33FF1FF1FE3FDFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FF
          FFFFFFFFFFFFFFCFFFFFFFFFFFE8FFFFF1FFF7FFFC73FF81FF9FFCFF1FE7FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFF
          FFFFFFFFFFFFFFE7FFFFFFFFFFF27FFFFCFFF9FFFF01FFE1FFFFFC3FCFF3FFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3F
          FFFFFFFFFFFFFFF9FFFFFFFFFFFC3FFFFE3FFCFFFFF1FFFFFFFFFF1FE7FBFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCF
          FFFFFFFFFFFFFFFEFFFFFFFFFFFF3FFFFFC7FE7FFFFFFFFFFFFFFF87FFFCFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7
          FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFE3FF3FFFFFFFFFFFFFFFC7FFFEFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1
          FFFFFFFFFFFFFFFFDFFFFFFFFFFFFFFFFFF8FF9FFFFFFFFFFFFFFFE3FFFF7FFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC
          7FFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFF1FE7FFFFFFFFFFFFFFF1FFFFBFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          3FFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFF8FF1FFFFFFFFFFFFFFF87FFFDFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          8FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFE3F9FFFFFFFFFFFFFFFC3FFFCFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          F3FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFF8FE7FFFFFFFFFFFFFFE1FFFF7FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          F9FFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFE3F3FFFFFFFFFFFFFFF1FFFFBFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FE7FFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFF9F9FFFFFFFFFFFFFFFCFFFF9FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FF9FFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFE3E7FFFFFFFFFFFFFFFFFFFEFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFE7FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFF9F3FFFFFFFFFFFFFFFFFFFF7F
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFF3FFFFFFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFC7CFFFFFFFFFFFFFFFFFFFF3F
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFCFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFF1E7FFFFFFFFFFFFFFFFFFFDF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFF3FFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFC7BFFFFFFFFFFFFFFFFFFFEF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFF9FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF38FFFFFFFFFFFFFFFFFFFEF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFE3FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFC67FFFFFFFFFFFFFFFFFFF3
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF9FFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFF13FFFFFFFFFFFFFFFFFFF9
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFC7FFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFCDFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFF3FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF2FFFFFFFFFFFFFFFFFFFE
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFF8FFFFFFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFF83FFFFFFFFFFFFFFFFFFF
          7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFE3FFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFF9FFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFF07FFFFFFFFFFFFFFFFFF
          DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFE7FFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFF
          F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFF9FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFE7FFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFC3FFFFFFFFFFFFFFFFF
          FDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFF1FFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFCFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFF
          FF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFF3FFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFF
          FFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFCFFFFFFFFFFFFFFFDFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFF
          FFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFE7FFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFF
          FFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFF8FFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFE7FFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFF
          FFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFF9FFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFE7FFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF8FFFFFFFFFFFFFF
          FFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF1FFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFC1FFFFFFFFFFFFF
          FFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFEFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFF4FFFFFFFFFFFFF
          FFFFF7FFC3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFF1FFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF93FFFFFFFFFFFF
          FFFFFDFF007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFCFFFFFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFFE4FFFFFFFFFFFF
          FFFFFF7E7F0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFF3FFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF23FFFFFFFFFFF
          FFFFFFCE7FE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFCFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFC8FFFFFFFFFFF
          FFFFFFF8FFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFE67FFFFFFFFFF
          FFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF9CFFFFFFFFFF
          FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFF
          FFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFCE7FFFFFFFFF
          FFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF31FFFFFFFFF
          FFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFF
          FFFFFFFFFFFFFFFFFF7FFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFCE7FFFFFFFF
          FFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFE73FFFFFFFF
          FFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFF
          FFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF38FFFFFFFF
          FFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFFFFF
          FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFC73FFFFFFF
          FFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFE79FFFFFFF
          FFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFF
          FFFFFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF9E7FFFFFF
          FFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFFFF
          FFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFE78FFFFFF
          FFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFF
          FFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFF3E3FFFFF
          FFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFF
          FFFFFFFFFFFFFFFFFFFFFDFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFDF9FFFFF
          FFFFFFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7FFFFF
          FFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFE7E7FFFF
          FFFFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFF
          FFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF9F8FFFF
          FFFFFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFF
          FFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFCFCFFFF
          FFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFF
          FFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF3F1FFF
          FFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFF
          FFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFCFC7FF
          FFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FF
          FFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFE3F1FF
          FFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3F
          FFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF9FC7F
          FFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7
          FFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFCFF3F
          FFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9
          FFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFF3FCF
          FFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          3FFFFFFFFFFFFFFFFFFFFFFFFFDFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFF9FE3
          FFFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          E7FFFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFE7FC
          FFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          F8FFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF3FE
          3FFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FF1FFFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFCFF
          8FFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFE3FFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFE3F
          E7FFFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFC7FFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFF9F
          F9FFFFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFF8FFFFFFFFFFFFFFFFFFFFFFFF9FFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFEF
          FE7FFFFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF1FFFFFFFFFFFFFFFFFFFFFFFE7FFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF3
          FF3FFFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFE3FFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFF9
          FFCFFFFFFFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFC7FFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFE
          7FF3FFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFF8FFFFFFFFFFFFFFFFFFFFFFFBFFFFFFFFFFFCFFFFFFFFFFFFFFFFFFFF
          3FF8FFFFFFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF
          CFFE7FFFFFFFFFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFF1FFFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF9FFFFFFFFFFFFFFFFFFF
          E3FF9FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFE3FFFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFE7FFFFFFFFFFFFFFFFFF
          F9FFE7FFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFF3FFFFFFFFFFFFFFFFFF
          FC7FF3FFFFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFFCFFFFFFFFFFFFFFFFFF
          FF3FFCFFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFF8FFFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFE7FFFFFFFFFFFFFFFFF
          FF8FFF3FFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFF0FFFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF9FFFFFFFFFFFFFFFFF
          FFE7FFDFFFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFF1FFFFFFFFFFFFFFFFFFFF3FFFFFFFFFFCFFFFFFFFFFFFFFFFF
          FFF9FFE7FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFE3FFFFFFFFFFFFFFFFFFFCFFFFFFFFFFF3FFFFFFFFFFFFFFFF
          FFFCFFF9FFFFFFFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFF3FFFFFFFFFFFFFFFFFFF3FFFFFFFFFFCFFFFFFFFFFFFFFFF
          FFFF3FFE7FFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFFFCFFFFFFFFFFE7FFFFFFFFFFFFFFF
          FFFF8FFF3FFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC3FFFFFFFFFFFFFFFFFF3FFFFFFFFFF9FFFFFFFFFFFFFFF
          FFFFE7FFCFFFFFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFFFCFFFFFFFFFFEFFFFFFFFFFFFFFF
          FFFFF9FFF3FFFFFFFFFFF7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFC3FFFFFFFFFFFFFFFFF7FFFFFFFFFF3FFFFFFFFFFFFFF
          FFFFFCFFFDFFFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFC7FFFFFFFFFFFFFFFFDFFFFFFFFFFDFFFFFFFFFFFFFF
          FFFFFE3FFF7FFFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFFFF3FFFFFFFFFE7FFFFFFFFFFFFF
          FFFFFFCFFFDFFFFFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFC3FFFFFFFFFFFFFFFDFFFFFFFFFF1FFFFFFFFFFFFF
          FFFFFFE7FFE7FFFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFC3FFFFFFFFFFFFFFF3FFFFFFFFFCFFFFFFFFFFFFF
          FFFFFFF1FFFBFFFFFFFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFFCFFFFFFFFFF3FFFFFFFFFFFF
          FFFFFFFC7FFEFFFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFFFFFFFFF3FFFFFFFFFCFFFFFFFFFFFF
          FFFFFFFF3FFF3FFFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFFFFFFFDFFFFFFFFFE7FFFFFFFFFFF
          FFFFFFFF8FFFDFFFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFF07FFFFFFFFFFFF3FFFFFFFFFBFFFFFFFFFFF
          FFFFFFFFE7FFF7FFFFE3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFF83FFFFFFFFFFFCFFFFFFFFFCFFFFFFFFFFF
          FFFFFFFFF8FFFBFFFFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF87FFFFFFFFFFF7FFFFFFFFE3FFFFFFFFFF
          FFFFFFFFFCFFFCFFFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC1FFFFFFFFFFCFFFFFFFFF9FFFFFFFFFF
          FFFFFFFFFF1FFF3FFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC1FFFFFFFFFE7FFFFFFFFEFFFFFFFFFF
          FFFFFFFFFFCFFF9FFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF07FFFFFFFFCFFFFFFFFF1FFFFFFFFF
          FFFFFFFFFFF3FFE7F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF83FFFFFFFE3FFFFFFFFCFFFFFFFFF
          FFFFFFFFFFF8FFFB8FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFFFFDFFFFFFFFE7FFFFFFFF
          FFFFFFFFFFFE3FFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF0FFFFFFE3FFFFFFFFBFFFFFFFF
          FFFFFFFFFFFF9FF17FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC1FFFFFDFFFFFFFFCFFFFFFFF
          FFFFFFFFFFFFC78FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE07FFFE3FFFFFFFF3FFFFFFF
          FFFFFFFFFFFFF07FE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC3FFFCFFFFFFFF9FFFFFFF
          FFFFFFFFFFFFE0FFFBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF07FF3FFFFFFFCFFFFFFF
          FFFFFFFFFFFE1F3FFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC0F9FFFFFFFE3FFFFFF
          FFFFFFFFFFE1FFCFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC03FFFFFFF9FFFFFF
          FFFFFFFFFE1FFFF3FF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC07FFFFFE7FFFFF
          FFFFFFFF83FFFFFCFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3E03FFFF3FFFFF
          FFFFFFC0FFFFFFFF3FE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFF00BFCFFFFF
          FFFF007FFFFFFFFFC7FBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFE0000BFF
          0000FFFFFFFFFFFFF1FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFFFFFBFF07
          FFFFFFFFFFFFFFFFFE7F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFFFFCFFFF
          FFFFFFFFFFFFFFFFFF8FBFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFF3FFF
          FFFFFFFFFFFFFFFFFFF09FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1FFFFFF9FFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFFFC7FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFF7FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE7FFFFF8FF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFE7F
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFF1F
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFFFFC7
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE1FFFFF1
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8FFFFF9
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE3FFFFE
          7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FFFF
          9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3FFFF
          CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFCFFFF
          F7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FFF
          FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7FF
          FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF9FF
          FF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1F
          FFC7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7
          FFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3
          FFF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFE
          7FFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          CFFF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          E7FFCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FE7FF3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FF9FF9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFF3FEFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFC7F3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFF8FCFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFF1EFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFE07FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFE7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
          FFFFFFFFFFFFFFFFFC00}
        mmHeight = 23019
        mmLeft = 61648
        mmTop = 254265
        mmWidth = 76200
        BandType = 4
      end
    end
    object ppReport1FooterBand1: TppFooterBand
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
  end
  object dtcContratos: TDataSource
    DataSet = tblContratos
    Left = 24
    Top = 16
  end
  object ppContrato: TppBDEPipeline
    DataSource = dtcContratos
    Left = 88
    Top = 16
  end
  object tblContratos: TUMZQuery
    CachedUpdates = True
    OnCalcFields = tblContratosCalcFields
    Connection = db
    
    SQL.Strings = (
      'SELECT Alunos.*, Matriculas.*, PlanosPagamento.*, Turmas.*'
      'FROM Turmas INNER JOIN '
      '(PlanosPagamento INNER JOIN (Alunos INNER JOIN Matriculas '
      'ON Alunos.Codigo = Matriculas.CodigoAluno) '
      'ON PlanosPagamento.Codigo = Matriculas.PlanoPagamento) '
      'ON Turmas.Codigo = Matriculas.Turma'
      'where'
      '(Matriculas.CodigoAluno = :Codigo) and'
      '(Matriculas.Turma = :Turma) and'
      '(Matriculas.AnoSemestre = :AnoSemestre) and'
      '(Turmas.AnoSemestre = :AnoSemestre)')
    Params.Data = {
      0100040006436F6469676F00030400000000000000055475726D610001020030
      0000000B416E6F53656D6573747265000304000000000000000B416E6F53656D
      657374726500030400000000000000}
    Left = 56
    Top = 16
    object tblContratosCodigo: TIntegerField
      FieldName = 'Codigo'
      Origin = 'Turmas.AnoSemestre'
    end
    object tblContratosNome: TStringField
      FieldName = 'Nome'
      Origin = 'Turmas.Codigo'
      Size = 45
    end
    object tblContratosDataNascimento: TDateTimeField
      FieldName = 'DataNascimento'
      Origin = 'Turmas.Serie'
    end
    object tblContratosCidadeNascimento: TStringField
      FieldName = 'CidadeNascimento'
      Origin = 'Turmas.Curso'
      Size = 22
    end
    object tblContratosEstadoNascimento: TStringField
      FieldName = 'EstadoNascimento'
      Origin = 'Turmas.Turno'
      Size = 2
    end
    object tblContratosEndereco: TStringField
      FieldName = 'Endereco'
      Origin = 'Turmas.Descricao'
      Size = 40
    end
    object tblContratosComplemento: TStringField
      FieldName = 'Complemento'
      Origin = 'Turmas.Contrato'
      Size = 10
    end
    object tblContratosCEP: TStringField
      FieldName = 'CEP'
      Origin = 'Turmas.Vagas'
      Size = 9
    end
    object tblContratosBairro: TStringField
      FieldName = 'Bairro'
      Origin = 'Turmas.HoraInicio'
    end
    object tblContratosCidade: TStringField
      FieldName = 'Cidade'
      Origin = 'Turmas.HoraFim'
    end
    object tblContratosEstado: TStringField
      FieldName = 'Estado'
      Origin = 'Turmas.DataInicio'
      Size = 2
    end
    object tblContratosTelefone1: TStringField
      FieldName = 'Telefone1'
      Origin = 'Turmas.DataFim'
      Size = 25
    end
    object tblContratosSexo: TStringField
      FieldName = 'Sexo'
      Origin = 'Turmas.IdadeConclusao'
      Size = 1
    end
    object tblContratosNacionalidade: TStringField
      FieldName = 'Nacionalidade'
      Origin = 'Turmas.DataConclusao'
      Size = 15
    end
    object tblContratosIdentidade: TStringField
      FieldName = 'Identidade'
      Origin = 'PlanosPagamento.Codigo'
      Size = 15
    end
    object tblContratosOrgaoExp: TStringField
      FieldName = 'OrgaoExp'
      Origin = 'PlanosPagamento.Turma'
      Size = 10
    end
    object tblContratosTurma: TStringField
      FieldName = 'Turma'
      Origin = 'PlanosPagamento.Parcelas'
      Size = 30
    end
    object tblContratosCPF: TStringField
      FieldName = 'CPF'
      Origin = 'PlanosPagamento.ValorCobrado'
      Size = 15
    end
    object tblContratosRM_CSM: TStringField
      FieldName = 'RM_CSM'
      Origin = 'PlanosPagamento.ValorContrato'
      Size = 15
    end
    object tblContratosNumeroMilitar: TStringField
      FieldName = 'NumeroMilitar'
      Origin = 'PlanosPagamento.TaxaMaterial'
      Size = 12
    end
    object tblContratosSerieMilitar: TStringField
      FieldName = 'SerieMilitar'
      Origin = 'PlanosPagamento.TaxaApostila'
      Size = 1
    end
    object tblContratosDataExpMilitar: TDateTimeField
      FieldName = 'DataExpMilitar'
      Origin = 'PlanosPagamento.Desconto'
    end
    object tblContratosLocalExpMilitar: TStringField
      FieldName = 'LocalExpMilitar'
      Origin = 'PlanosPagamento.Matricula'
      Size = 15
    end
    object tblContratosOrganizacaoMilitar: TStringField
      FieldName = 'OrganizacaoMilitar'
      Origin = 'PlanosPagamento.Apartir'
      Size = 10
    end
    object tblContratosTipoDocumento: TStringField
      FieldName = 'TipoDocumento'
      Origin = 'PlanosPagamento.NumeroTaxasMaterial'
      Size = 10
    end
    object tblContratosPai: TStringField
      FieldName = 'Pai'
      Origin = 'Alunos.Codigo'
      Size = 45
    end
    object tblContratosMae: TStringField
      FieldName = 'Mae'
      Origin = 'Alunos.Nome'
      Size = 40
    end
    object tblContratosResponsavel: TStringField
      FieldName = 'Responsavel'
      Origin = 'Alunos.DataNascimento'
      Size = 30
    end
    object tblContratosDataNascimentoResponsavel: TDateTimeField
      FieldName = 'DataNascimentoResponsavel'
      Origin = 'Alunos.CidadeNascimento'
    end
    object tblContratosNaturalidadeResponsavel: TStringField
      FieldName = 'NaturalidadeResponsavel'
      Origin = 'Alunos.EstadoNascimento'
      Size = 30
    end
    object tblContratosUFNaturalidadeResponsavel: TStringField
      FieldName = 'UFNaturalidadeResponsavel'
      Origin = 'Alunos.Endereco'
      Size = 2
    end
    object tblContratosSexoResponsavel: TStringField
      FieldName = 'SexoResponsavel'
      Origin = 'Alunos.Complemento'
      Size = 1
    end
    object tblContratosPaiResponsavel: TStringField
      FieldName = 'PaiResponsavel'
      Origin = 'Alunos.CEP'
      Size = 45
    end
    object tblContratosMaeResponsavel: TStringField
      FieldName = 'MaeResponsavel'
      Origin = 'Alunos.Bairro'
      Size = 45
    end
    object tblContratosEstadoCivilResponsavel: TStringField
      FieldName = 'EstadoCivilResponsavel'
      Origin = 'Alunos.Cidade'
    end
    object tblContratosNomeConjuge: TStringField
      FieldName = 'NomeConjuge'
      Origin = 'Alunos.Estado'
      Size = 30
    end
    object tblContratosDataNascimentoConjuge: TDateTimeField
      FieldName = 'DataNascimentoConjuge'
      Origin = 'Alunos.Telefone1'
    end
    object tblContratosCPF_Responsavel: TStringField
      FieldName = 'CPF_Responsavel'
      Origin = 'Alunos.Sexo'
    end
    object tblContratosRGResponsavel: TStringField
      FieldName = 'RGResponsavel'
      Origin = 'Alunos.Nacionalidade'
      Size = 15
    end
    object tblContratosEnderecoResponsavel: TStringField
      FieldName = 'EnderecoResponsavel'
      Origin = 'Alunos.Identidade'
      Size = 40
    end
    object tblContratosComplementoResponsavel: TStringField
      FieldName = 'ComplementoResponsavel'
      Origin = 'Alunos.OrgaoExp'
      Size = 40
    end
    object tblContratosCidadeResponsavel: TStringField
      FieldName = 'CidadeResponsavel'
      Origin = 'Alunos.Turma'
      Size = 30
    end
    object tblContratosCEPResponsavel: TStringField
      FieldName = 'CEPResponsavel'
      Origin = 'Alunos.CPF'
      Size = 9
    end
    object tblContratosUFResponsavel: TStringField
      FieldName = 'UFResponsavel'
      Origin = 'Alunos.RM_CSM'
      Size = 2
    end
    object tblContratosTelefoneResponsavel: TStringField
      FieldName = 'TelefoneResponsavel'
      Origin = 'Alunos.NumeroMilitar'
      Size = 30
    end
    object tblContratosTelefone2: TStringField
      FieldName = 'Telefone2'
      Origin = 'Alunos.SerieMilitar'
      Size = 25
    end
    object tblContratosFuncionario: TStringField
      FieldName = 'Funcionario'
      Origin = 'Alunos.DataExpMilitar'
    end
    object tblContratosVersaoCracha: TIntegerField
      FieldName = 'VersaoCracha'
      Origin = 'Alunos.LocalExpMilitar'
    end
    object tblContratosCodigoAlunoIndicado: TIntegerField
      FieldName = 'CodigoAlunoIndicado'
      Origin = 'Alunos.OrganizacaoMilitar'
    end
    object tblContratosEstadoCivil: TStringField
      FieldName = 'EstadoCivil'
      Origin = 'Alunos.TipoDocumento'
    end
    object tblContratosDataRevisao: TDateTimeField
      FieldName = 'DataRevisao'
      Origin = 'Alunos.Pai'
    end
    object tblContratosNomeSemAcento: TStringField
      FieldName = 'NomeSemAcento'
      Origin = 'Alunos.Mae'
      Size = 45
    end
    object tblContratosEmail: TStringField
      FieldName = 'Email'
      Origin = 'Alunos.Responsavel'
      Size = 255
    end
    object tblContratosEscolaOrigem: TStringField
      FieldName = 'EscolaOrigem'
      Origin = 'Alunos.DataNascimentoResponsavel'
      Size = 50
    end
    object tblContratosSituacao: TSmallintField
      FieldName = 'Situacao'
      Origin = 'Alunos.NaturalidadeResponsavel'
    end
    object tblContratosCodigoAluno: TIntegerField
      FieldName = 'CodigoAluno'
      Origin = 'Alunos.UFNaturalidadeResponsavel'
    end
    object tblContratosTurma_1: TStringField
      FieldName = 'Turma_1'
      Origin = 'Alunos.SexoResponsavel'
      Size = 15
    end
    object tblContratosAnoSemestre_1: TSmallintField
      DisplayLabel = 'Ano/Sem.'
      FieldName = 'AnoSemestre_1'
      Origin = 'Turmas.AnoSemestre'
      DisplayFormat = '0000/0'
    end
    object tblContratosDataEmissao: TDateTimeField
      FieldName = 'DataEmissao'
      Origin = 'Alunos.EstadoCivilResponsavel'
    end
    object tblContratosUsuario: TStringField
      FieldName = 'Usuario'
      Origin = 'Alunos.NomeConjuge'
      Size = 30
    end
    object tblContratosPlanoPagamento: TIntegerField
      FieldName = 'PlanoPagamento'
      Origin = 'Alunos.DataNascimentoConjuge'
    end
    object tblContratosSituacao_1: TSmallintField
      FieldName = 'Situacao_1'
      Origin = 'Alunos.CPF_Responsavel'
    end
    object tblContratosImpresso: TBooleanField
      FieldName = 'Impresso'
      Origin = 'Alunos.RGResponsavel'
    end
    object tblContratosDataSaida: TDateTimeField
      FieldName = 'DataSaida'
      Origin = 'Alunos.EnderecoResponsavel'
    end
    object tblContratosPlanoDesconto: TIntegerField
      FieldName = 'PlanoDesconto'
      Origin = 'Alunos.ComplementoResponsavel'
    end
    object tblContratosDiploma: TBooleanField
      FieldName = 'Diploma'
      Origin = 'Alunos.CidadeResponsavel'
    end
    object tblContratosCodigo_1: TIntegerField
      FieldName = 'Codigo_1'
      Origin = 'Alunos.CEPResponsavel'
    end
    object tblContratosTurma_2: TStringField
      FieldName = 'Turma_2'
      Origin = 'Alunos.UFResponsavel'
      Size = 15
    end
    object tblContratosParcelas: TSmallintField
      FieldName = 'Parcelas'
      Origin = 'Alunos.TelefoneResponsavel'
    end
    object tblContratosValorCobrado: TFloatField
      FieldName = 'ValorCobrado'
      Origin = 'Alunos.Telefone2'
      DisplayFormat = '###,###,##0.00'
    end
    object tblContratosValorContrato: TFloatField
      FieldName = 'ValorContrato'
      Origin = 'Alunos.Funcionario'
      DisplayFormat = '###,###,##0.00'
    end
    object tblContratosTaxaMaterial: TFloatField
      FieldName = 'TaxaMaterial'
      Origin = 'Alunos.VersaoCracha'
    end
    object tblContratosTaxaApostila: TFloatField
      FieldName = 'TaxaApostila'
      Origin = 'Alunos.CodigoAlunoIndicado'
    end
    object tblContratosDesconto: TFloatField
      FieldName = 'Desconto'
      Origin = 'Alunos.EstadoCivil'
    end
    object tblContratosMatricula: TFloatField
      FieldName = 'Matricula'
      Origin = 'Alunos.DataRevisao'
    end
    object tblContratosApartir: TDateTimeField
      FieldName = 'Apartir'
      Origin = 'Alunos.NomeSemAcento'
    end
    object tblContratosNumeroTaxasMaterial: TSmallintField
      FieldName = 'NumeroTaxasMaterial'
      Origin = 'Alunos.Email'
    end
    object tblContratosAnoSemestre: TSmallintField
      FieldName = 'AnoSemestre'
      Origin = 'Alunos.EscolaOrigem'
    end
    object tblContratosCodigo_2: TStringField
      FieldName = 'Codigo_2'
      Origin = 'Alunos.Situacao'
      Size = 5
    end
    object tblContratosSerie: TSmallintField
      FieldName = 'Serie'
      Origin = 'Matriculas.CodigoAluno'
    end
    object tblContratosCurso: TStringField
      FieldName = 'Curso'
      Origin = 'Matriculas.Turma'
      Size = 15
    end
    object tblContratosTurno: TStringField
      FieldName = 'Turno'
      Origin = 'Matriculas.Periodo'
      Size = 1
    end
    object tblContratosDescricao: TStringField
      FieldName = 'Descricao'
      Origin = 'Matriculas.Sequencia'
      Size = 40
    end
    object tblContratosContrato: TStringField
      FieldName = 'Contrato'
      Origin = 'Matriculas.DataEmissao'
      Size = 50
    end
    object tblContratosVagas: TSmallintField
      FieldName = 'Vagas'
      Origin = 'Matriculas.Usuario'
    end
    object tblContratosHoraInicio: TDateTimeField
      FieldName = 'HoraInicio'
      Origin = 'Matriculas.PlanoPagamento'
    end
    object tblContratosHoraFim: TDateTimeField
      FieldName = 'HoraFim'
      Origin = 'Matriculas.Situacao'
    end
    object tblContratosDataInicio: TDateTimeField
      FieldName = 'DataInicio'
      Origin = 'Matriculas.Impresso'
      DisplayFormat = 'dd/mm/yyyy'
    end
    object tblContratosDataFim: TDateTimeField
      FieldName = 'DataFim'
      Origin = 'Matriculas.DataSaida'
      DisplayFormat = 'dd/mm/yyyy'
    end
    object tblContratosIdadeConclusao: TSmallintField
      FieldName = 'IdadeConclusao'
      Origin = 'Matriculas.PlanoDesconto'
    end
    object tblContratosDataConclusao: TDateTimeField
      FieldName = 'DataConclusao'
      Origin = 'Matriculas.Diploma'
    end
    object tblContratosTeste: TStringField
      FieldName = 'Teste'
      Calculated = True
    end
  end
end

