object frmSplash: TfrmSplash
  Left = 266
  Top = 240
  BorderIcons = []
  BorderStyle = bsNone
  ClientHeight = 97
  ClientWidth = 326
  Color = clBtnFace
  Font.Charset = ANSI_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = []
  OldCreateOrder = True
  Position = poScreenCenter
  Visible = True
  OnPaint = FormPaint
  PixelsPerInch = 96
  TextHeight = 14
  object Bevel1: TBevel
    Left = 0
    Top = 0
    Width = 326
    Height = 97
    Align = alClient
    Style = bsRaised
  end
  object lblAguarde: TLabel
    Left = 0
    Top = 17
    Width = 325
    Height = 16
    Alignment = taCenter
    AutoSize = False
    Caption = 'Aguarde...'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Transparent = True
  end
  object Label1: TLabel
    Left = 0
    Top = 43
    Width = 326
    Height = 17
    Alignment = taCenter
    AutoSize = False
    Caption = 'Conectando com o Banco de Dados.'
    Font.Charset = ANSI_CHARSET
    Font.Color = clWindowText
    Font.Height = -13
    Font.Name = 'Arial'
    Font.Style = []
    ParentFont = False
    Transparent = True
  end
  object pgbStatus: TProgressBar
    Left = 7
    Top = 72
    Width = 314
    Height = 19
    Smooth = True
    Step = 1
    TabOrder = 0
    Visible = False
  end
end
