object fExibeImagem: TfExibeImagem
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  Caption = 'Documento'
  ClientHeight = 301
  ClientWidth = 412
  Color = clHighlightText
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  PixelsPerInch = 96
  TextHeight = 13
  object ciDocumento: TCropImage
    Left = 0
    Top = 0
    Width = 412
    Height = 301
    Align = alClient
    Border = False
    ToolColor = clWhite
    ExplicitWidth = 410
    ExplicitHeight = 50
  end
end
