; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "UNIMESTRE Topdata"
#define MyAppVersion "2.19.0.0"
#define MyAppPublisher "Unimestre Serviço de Apoio Educacional LTDA"
#define MyAppURL "http://unimestre.com"
#define MyAppExeName "Topdata.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{7747F03F-865C-47C6-B860-09C82EADCB2F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={reg:HKLM\Software\Uninformare\UNIMESTRE,UniMestreDir|{sd}\UNIMESTRE}
DisableDirPage=yes
DisableProgramGroupPage=yes
OutputBaseFilename=Instalador do Unimestre Topdata {#MyAppVersion}
OutputDir=..\..\..\tags\testing
Compression=lzma
SolidCompression=yes

[Languages]
Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: ..\exe\Topdata.exe; DestDir: {app}\programas; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: ..\fontes\Imagens\Direita-normall.JPG; DestDir: {app}\programas\Imagens
Source: ..\fontes\Imagens\Esquerda-invertidaa.JPG; DestDir: {app}\programas\Imagens
Source: ..\fontes\Imagens\nenhum.JPG; DestDir: {app}\programas\Imagens
Source: ..\fontes\dependencia_catraca_topdata\dotNetFx35setup.exe; DestDir: {app}; Flags: ignoreversion

[Icons]
Name: {commonprograms}\{#MyAppName}; Filename: {app}\{#MyAppExeName}
Name: {commondesktop}\{#MyAppName}; Filename: {app}\{#MyAppExeName}; Tasks: desktopicon

[Run]
Filename: {app}\dotNetFx35setup.exe; Description: "{cm:LaunchProgram,{#StringChange('Microsoft .NET Framework 3.5', '&', '&&')}}"; Flags: shellexec nowait postinstall 
Filename: {app}\programas\{#MyAppExeName}; Description: {cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}; Flags: nowait postinstall skipifsilent
[INI]
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Servidor; String: localhost; Flags: createkeyifdoesntexist; Tasks: ; Languages: 
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Banco; String: unimestre; Flags: createkeyifdoesntexist
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Usuario; String: academico; Flags: createkeyifdoesntexist
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Senha; String: 44C07AB24C83C571AF2744F2244EF331DE; Flags: createkeyifdoesntexist
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Porta; String: 3306; Flags: createkeyifdoesntexist
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Protocolo; String: mysql-5; Flags: createkeyifdoesntexist
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Usa.Start; String: 0; Flags: createkeyifdoesntexist
Filename: {app}\programas\unimestre.ini; Section: Conexao; Key: Start.Banco; String: umstart; Flags: createkeyifdoesntexist
