unit uPSI_uScriptFunctions;
{
This file has been generated by UnitParser v0.6, written by M. Knight
and updated by NP. v/d Spek and George Birbilis.
Source Code from Carlo Kok has been used to implement various sections of
UnitParser. Components of ROPS are used in the construction of UnitParser,
code implementing the class wrapper is taken from Carlo Kok's conv utility

}
interface

uses
   SysUtils
  ,Classes
  ,uPSComponent
  ,uPSRuntime
  ,uPSCompiler
  ;

type
(*----------------------------------------------------------------------------*)
  TPSImport_uScriptFunctions = class(TPSPlugin)
  protected
    procedure CompileImport1(CompExec: TPSScript); override;
    procedure ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter); override;
  end;


{ compile-time registration functions }
procedure SIRegister_uScriptFunctions(CL: TPSPascalCompiler);

{ run-time registration functions }
procedure RIRegister_uScriptFunctions_Routines(S: TPSExec);

procedure Register;

implementation


uses
   Forms
  ,Controls
  ,Windows
  ,IniFiles
  ,Graphics
  ,StrUtils
  ,DateUtils
  ,Math
  ,Variants
  ,Dialogs
  ,uScriptFunctions
  ;


procedure Register;
begin
  RegisterComponents('Pascal Script', [TPSImport_uScriptFunctions]);
end;

(* === compile-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure SIRegister_uScriptFunctions(CL: TPSPascalCompiler);
begin
 CL.AddDelphiFunction('Function Esquerda( sTexto : Variant; iQtd : Variant) : string');
 CL.AddDelphiFunction('Function Direita( sTexto : Variant; iQtd : Variant) : string');
 CL.AddDelphiFunction('Function Meio( sTexto : Variant; Posicao, iQtd : Variant) : string');
 CL.AddDelphiFunction('Function Tamanho( sTexto : Variant) : string');
 CL.AddDelphiFunction('Function Maiuscula( sTexto : Variant) : string');
 CL.AddDelphiFunction('Function Minuscula( sTexto : Variant) : string');
 CL.AddDelphiFunction('Function Substituir( sTexto : Variant; OldValue : Variant; NewValue : Variant) : string');
 CL.AddDelphiFunction('Function Soma( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Subtrai( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Divide( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function RestoDiv( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function DivNumero( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Potencia( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Multiplica( iNumero : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Maior( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Menor( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function Media( iNumero1 : Variant; iNumero2 : Variant) : string');
 CL.AddDelphiFunction('Function FormataNumero( sTexto : Variant; sFormato : Variant) : string');
 CL.AddDelphiFunction('Function FormataData( sTexto : Variant; sData : Variant) : string');
 CL.AddDelphiFunction('Function Dia( sData : Variant) : string');
 CL.AddDelphiFunction('Function Mes( sData : Variant) : string');
 CL.AddDelphiFunction('Function Ano( sData : Variant) : string');
 CL.AddDelphiFunction('Function Hora( sData : Variant) : string');
 CL.AddDelphiFunction('Function Minuto( sData : Variant) : string');
 CL.AddDelphiFunction('Function Segundo( sData : Variant) : string');
 CL.AddDelphiFunction('Function DiaDaSemana( sData : Variant) : string');
 CL.AddDelphiFunction('Function DiaDoAno( sData : Variant) : string');
 CL.AddDelphiFunction('Function SomaData( sData1 : Variant; sData2 : Variant) : string');
 CL.AddDelphiFunction('Function DifData( sData1 : Variant; sData2 : Variant) : string');
 CL.AddDelphiFunction('Function Hoje( ) : string');
 CL.AddDelphiFunction('Function DV10( ds_codigo, cd_banco : Variant) : string');
 CL.AddDelphiFunction('Function DV10BB( strCodigo : Variant) : string');
 CL.AddDelphiFunction('Function DV11( ds_codigo, cd_tipo, cd_banco : Variant) : string');
 CL.AddDelphiFunction('Function DV11BB( strCodigo : Variant) : string');
 CL.AddDelphiFunction('Function DV44( strCodigo : Variant) : string');
 CL.AddDelphiFunction('Function DV440( strCodigo : Variant) : string');
 CL.AddDelphiFunction('Function ToDateTime( sTexto : Variant) : TDateTime');
 CL.AddDelphiFunction('Function ToExtended( sNumero : Variant) : Extended');
 CL.AddDelphiFunction('Function VariantToType( vVariant : Variant; varType : Word) : Variant');
end;

(* === run-time registration functions === *)
(*----------------------------------------------------------------------------*)
procedure RIRegister_uScriptFunctions_Routines(S: TPSExec);
begin
 S.RegisterDelphiFunction(@Esquerda, 'Esquerda', cdRegister);
 S.RegisterDelphiFunction(@Direita, 'Direita', cdRegister);
 S.RegisterDelphiFunction(@Meio, 'Meio', cdRegister);
 S.RegisterDelphiFunction(@Tamanho, 'Tamanho', cdRegister);
 S.RegisterDelphiFunction(@Maiuscula, 'Maiuscula', cdRegister);
 S.RegisterDelphiFunction(@Minuscula, 'Minuscula', cdRegister);
 S.RegisterDelphiFunction(@Substituir, 'Substituir', cdRegister);
 S.RegisterDelphiFunction(@Soma, 'Soma', cdRegister);
 S.RegisterDelphiFunction(@Subtrai, 'Subtrai', cdRegister);
 S.RegisterDelphiFunction(@Divide, 'Divide', cdRegister);
 S.RegisterDelphiFunction(@RestoDiv, 'RestoDiv', cdRegister);
 S.RegisterDelphiFunction(@DivNumero, 'DivNumero', cdRegister);
 S.RegisterDelphiFunction(@Potencia, 'Potencia', cdRegister);
 S.RegisterDelphiFunction(@Multiplica, 'Multiplica', cdRegister);
 S.RegisterDelphiFunction(@Maior, 'Maior', cdRegister);
 S.RegisterDelphiFunction(@Menor, 'Menor', cdRegister);
 S.RegisterDelphiFunction(@Media, 'Media', cdRegister);
 S.RegisterDelphiFunction(@FormataNumero, 'FormataNumero', cdRegister);
 S.RegisterDelphiFunction(@FormataData, 'FormataData', cdRegister);
 S.RegisterDelphiFunction(@Dia, 'Dia', cdRegister);
 S.RegisterDelphiFunction(@Mes, 'Mes', cdRegister);
 S.RegisterDelphiFunction(@Ano, 'Ano', cdRegister);
 S.RegisterDelphiFunction(@Hora, 'Hora', cdRegister);
 S.RegisterDelphiFunction(@Minuto, 'Minuto', cdRegister);
 S.RegisterDelphiFunction(@Segundo, 'Segundo', cdRegister);
 S.RegisterDelphiFunction(@DiaDaSemana, 'DiaDaSemana', cdRegister);
 S.RegisterDelphiFunction(@DiaDoAno, 'DiaDoAno', cdRegister);
 S.RegisterDelphiFunction(@SomaData, 'SomaData', cdRegister);
 S.RegisterDelphiFunction(@DifData, 'DifData', cdRegister);
 S.RegisterDelphiFunction(@Hoje, 'Hoje', cdRegister);
 S.RegisterDelphiFunction(@DV10, 'DV10', cdRegister);
 S.RegisterDelphiFunction(@DV10BB, 'DV10BB', cdRegister);
 S.RegisterDelphiFunction(@DV11, 'DV11', cdRegister);
 S.RegisterDelphiFunction(@DV11BB, 'DV11BB', cdRegister);
 S.RegisterDelphiFunction(@DV44, 'DV44', cdRegister);
 S.RegisterDelphiFunction(@DV440, 'DV440', cdRegister);
 S.RegisterDelphiFunction(@ToDateTime, 'ToDateTime', cdRegister);
 S.RegisterDelphiFunction(@ToExtended, 'ToExtended', cdRegister);
 S.RegisterDelphiFunction(@VariantToType, 'VariantToType', cdRegister);
end;



{ TPSImport_uScriptFunctions }
(*----------------------------------------------------------------------------*)
procedure TPSImport_uScriptFunctions.CompileImport1(CompExec: TPSScript);
begin
  SIRegister_uScriptFunctions(CompExec.Comp);
end;
(*----------------------------------------------------------------------------*)
procedure TPSImport_uScriptFunctions.ExecImport1(CompExec: TPSScript; const ri: TPSRuntimeClassImporter);
begin
  RIRegister_uScriptFunctions(ri);
  RIRegister_uScriptFunctions_Routines(CompExec.Exec); // comment it if no routines
end;
(*----------------------------------------------------------------------------*)


end.
