const
   SEventAfterInstall = 'Unimestre Catracas successfully installed';
   SEventAfterUninstall = 'Unimestre Catracas successfully uninstalled';
   SEventOnContinue = 'Resuming Unimestre Catracas';
   SEventOnPause = 'Pausing Unimestre Catracas';
   SEventOnShutdown = 'Shutting down Unimestre Catracas';
   SEventOnStart = 'Starting Unimestre Catracas';
   SEventOnStop = 'Stopping Unimestre Catracas';
   SEventDeviceErrorFmt = '[%d] %s error from %s:%d';   
